package main

// aowSubCategoryOverrides: strength/dexterity/quality/magic/faith/arcane
// sub-category per ashes_of_war item, generated by tools/aow_categories from
// EquipParamGem's defaultWepAttr (the affinity the Ash of War locks in when
// applied) -- see tools/aow_categories/generate.py for the full mapping
// rationale and docs/ITEM_IDS.md for the summary. Items with no forced
// affinity (Standard/guard/parry/bow-only skills) are intentionally absent
// -- no sub-category, not an arbitrary one.
//
// Regenerate: cd tools/aow_categories && ../.venv/bin/python3 generate.py
var aowSubCategoryOverrides = map[uint32]string{
	0x80002710: "Strength",  // Lion's Claw
	0x80002774: "Dexterity", // Impaling Thrust
	0x800027D8: "Dexterity", // Piercing Fang
	0x8000283C: "Dexterity", // Spinning Slash
	0x80002904: "Quality",   // Charge Forth
	0x80002968: "Strength",  // Stamp (Upward Cut)
	0x800029CC: "Strength",  // Stamp (Sweep)
	0x80002A30: "Arcane",    // Blood Tax
	0x80002A94: "Dexterity", // Repeating Thrust
	0x80002AF8: "Strength",  // Wild Strikes
	0x80002B5C: "Quality",   // Spinning Strikes
	0x80002BC0: "Dexterity", // Double Slash
	0x80002C24: "Faith",     // Prelate's Charge
	0x80002C88: "Dexterity", // Unsheathe
	0x80002CEC: "Quality",   // Square Off
	0x80002D50: "Quality",   // Giant Hunt
	0x80002E18: "Magic",     // Loretta's Slash
	0x80002E7C: "Arcane",    // Poison Moth Flight
	0x80002EE0: "Magic",     // Spinning Weapon
	0x80002FA8: "Quality",   // Storm Assault
	0x8000300C: "Quality",   // Stormcaller
	0x80003070: "Dexterity", // Sword Dance
	0x80004E20: "Magic",     // Glintblade Phalanx
	0x80004E84: "Faith",     // Sacred Blade
	0x80004EE8: "Magic",     // Ice Spear
	0x80004F4C: "Magic",     // Glintstone Pebble
	0x80004FB0: "Arcane",    // Bloody Slash
	0x80005014: "Arcane",    // Lifesteal Fist
	0x800050DC: "Strength",  // Eruption
	0x80005140: "Faith",     // Prayerful Strike
	0x800051A4: "Magic",     // Gravitas
	0x80005208: "Quality",   // Storm Blade
	0x800052D0: "Strength",  // Earthshaker
	0x80005334: "Faith",     // Golden Land
	0x80005398: "Strength",  // Flaming Strike
	0x80005460: "Dexterity", // Thunderbolt
	0x800054C4: "Dexterity", // Lightning Slash
	0x80005528: "Magic",     // Carian Grandeur
	0x8000558C: "Magic",     // Carian Greatsword
	0x800055F0: "Quality",   // Vacuum Slice
	0x80005654: "Faith",     // Black Flame Tornado
	0x800056B8: "Faith",     // Sacred Ring of Light
	0x80005780: "Arcane",    // Blood Blade
	0x800057E4: "Quality",   // Phantom Slash
	0x80005848: "Arcane",    // Spectral Lance
	0x800058AC: "Magic",     // Chilling Mist
	0x80005910: "Arcane",    // Poisonous Mist
	0x80007724: "Magic",     // Carian Retaliation
	0x800077EC: "Faith",     // Golden Parry
	0x80007918: "Magic",     // Thops's Barrier
	0x8000C3B4: "Magic",     // Hoarfrost Stomp
	0x8000C418: "Quality",   // Storm Stomp
	0x8000C47C: "Strength",  // Kick
	0x8000C4E0: "Dexterity", // Lightning Ram
	0x8000C544: "Strength",  // Flame of the Redmanes
	0x8000C5A8: "Strength",  // Ground Slam
	0x8000C60C: "Faith",     // Golden Slam
	0x8000C670: "Magic",     // Waves of Darkness
	0x8000C6D4: "Strength",  // Hoarah Loux's Earthshaker
	0x8000EA60: "Quality",   // Determination
	0x8000EAC4: "Quality",   // Royal Knight's Resolve
	0x8000EB28: "Arcane",    // Assassin's Gambit
	0x8000EB8C: "Faith",     // Golden Vow
	0x8000EBF0: "Faith",     // Sacred Order
	0x8000EC54: "Faith",     // Shared Order
	0x8000ECB8: "Arcane",    // Seppuku
	0x8000ED1C: "Strength",  // Cragblade
	0x8000FDE8: "Strength",  // Barbaric Roar
	0x8000FE4C: "Strength",  // War Cry
	0x8000FEB0: "Dexterity", // Beast's Roar
	0x8000FF14: "Strength",  // Troll's Roar
	0x8000FF78: "Strength",  // Braggart's Roar
	0x80011170: "Strength",  // Endure
	0x800111D4: "Faith",     // Vow of the Indomitable
	0x80011238: "Faith",     // Holy Ground
	0x80013880: "Dexterity", // Quickstep
	0x800138E4: "Dexterity", // Bloodhound's Step
	0x80013948: "Dexterity", // Raptor of the Mists
	0x80014C08: "Arcane",    // White Shadow's Lure
	0x80030DA4: "Faith",     // Aspects of the Crucible: Wings
	0x80061A80: "Strength",  // Spinning Gravity Thrust
	0x80062250: "Dexterity", // Piercing Throw
	0x80062638: "Dexterity", // Scattershot Throw
	0x800631F0: "Dexterity", // Raging Beast
	0x800635D8: "Dexterity", // Savage Claws
	0x80063DA8: "Dexterity", // Blind Spot
	0x80064190: "Dexterity", // Swift Slash
	0x80064578: "Dexterity", // Overhead Stance
	0x80064960: "Quality",   // Wing Stance
	0x80064D48: "Dexterity", // Blinkbolt
	0x80065130: "Faith",     // Flame Skewer
	0x80065518: "Strength",  // Savage Lion's Claw
	0x80065900: "Magic",     // Divine Beast Frost Stomp
	0x80065CE8: "Faith",     // Flame Spear
	0x800660D0: "Magic",     // Carian Sovereignty
	0x800664B8: "Arcane",    // Shriek of Sorrow
	0x80067070: "Magic",     // Ghostflame Call
	0x8007B4A8: "Arcane",    // The Poison Flower Blooms Twice
}
