// Code generated by tools/key_item_categories/generate.py. DO NOT EDIT.
// Ground truth: EquipParamGoods sortGroupId/goodsType/refCategory decoded
// from the fixture save, plus a short wiki-verified list for the handful
// of items fields alone can't settle -- see docs/ITEM_IDS.md.
package main

// keyItemSubCategoryOverrides replaces key_items' old dump-bucket
// subcategories ("Inactive Great Runes + Keys + Medallions" etc, see
// ITEM_IDS.md) with a 17-way taxonomy. Applied in main()'s override loop.
var keyItemSubCategoryOverrides = map[uint32]string{
	0x40000073: "Quest Items",            // Memory of Grace
	0x40000087: "Great Runes",            // Phantom Great Rune
	0x400004D8: "Quest Items",            // Shabriri Grape
	0x4000082A: "Quest Items",            // Deathroot
	0x40000852: "Quest Items",            // Celestial Dew
	0x40001F40: "Keys & Medallions",      // Stonesword Key
	0x40001F4A: "Keys & Medallions",      // Rusty Key
	0x40001FA9: "Keys & Medallions",      // Dectus Medallion (Left)
	0x40001FAA: "Keys & Medallions",      // Dectus Medallion (Right)
	0x40001FAB: "Keys & Medallions",      // Rold Medallion
	0x40001FAD: "Keys & Medallions",      // Academy Glintstone Key (Variant)
	0x40001FAF: "Keys & Medallions",      // Carian Inverted Statue
	0x40001FB9: "Quest Items",            // Dark Moon Ring
	0x40001FBE: "Quest Items",            // Fingerprint Grape
	0x40001FC0: "Quest Items",            // Tonic of Forgetfulness
	0x40001FC1: "Quest Items",            // Serpent's Amnion
	0x40001FC6: "Keys & Medallions",      // Drawing-Room Key
	0x40001FC8: "Quest Items",            // Rya's Necklace
	0x40001FC9: "Clues & Maps",           // Volcano Manor Invitation
	0x40001FCE: "Quest Items",            // Amber Starlight
	0x40001FCF: "Quest Items",            // Seluvis's Introduction
	0x40001FD0: "Quest Items",            // Sellen's Primal Glintstone
	0x40001FD2: "Quest Items",            // Miniature Ranni (Variant)
	0x40001FD3: "Quest Items",            // Asimi, Silver Tear
	0x40001FD4: "Great Runes",            // Godrick's Great Rune
	0x40001FD5: "Great Runes",            // Radahn's Great Rune
	0x40001FD6: "Great Runes",            // Morgott's Great Rune
	0x40001FD7: "Great Runes",            // Rykard's Great Rune
	0x40001FD8: "Great Runes",            // Mohg's Great Rune
	0x40001FD9: "Great Runes",            // Malenia's Great Rune
	0x40001FDB: "Quest Items",            // Lord of Blood's Favor
	0x40001FDE: "Crafting Tools",         // Spirit Calling Bell
	0x40001FDF: "Quest Items",            // Fingerslayer Blade
	0x40001FE1: "Crafting Tools",         // Sewing Needle
	0x40001FE2: "Crafting Tools",         // Gold Sewing Needle
	0x40001FE3: "Crafting Tools",         // Tailoring Tools
	0x40001FE4: "Quest Items",            // Seluvis's Potion
	0x40001FE6: "Quest Items",            // Amber Draught
	0x40001FE8: "Quest Items",            // Dancer's Castanets
	0x40001FE9: "Keys & Medallions",      // Sellian Sealbreaker
	0x40001FEB: "Quest Items",            // Chrysalids' Memento
	0x40001FEC: "Quest Items",            // Black Knifeprint
	0x40001FEE: "Quest Items",            // Academy Glintstone Key
	0x40001FEF: "Keys & Medallions",      // Haligtree Secret Medallion (Left)
	0x40001FF0: "Keys & Medallions",      // Haligtree Secret Medallion (Right)
	0x40001FF6: "Mending Runes",          // Mending Rune of Perfect Order
	0x40001FF7: "Mending Runes",          // Mending Rune of the Death-Prince
	0x40001FF8: "Mending Runes",          // Mending Rune of the Fell Curse
	0x40001FF9: "Quest Items",            // Larval Tear
	0x40001FFA: "Keys & Medallions",      // Imbued Sword Key
	0x40001FFB: "Quest Items",            // Miniature Ranni
	0x40001FFC: "Crafting Tools",         // Golden Tailoring Tools
	0x40001FFD: "Quest Items",            // Iji's Confession
	0x40001FFE: "Clues & Maps",           // Knifeprint Clue
	0x40001FFF: "Quest Items",            // Cursemark of Death
	0x40002000: "Quest Items",            // Asimi's Husk
	0x40002001: "Quest Items",            // Seedbed Curse
	0x40002002: "Quest Items",            // The Stormhawk King
	0x40002003: "Quest Items",            // Asimi, Silver Chrysalid
	0x40002005: "Keys & Medallions",      // Sewer-Gaol Key
	0x40002006: "Clues & Maps",           // Meeting Place Map
	0x40002007: "Keys & Medallions",      // Discarded Palace Key
	0x4000201E: "Quest Items",            // Alexander's Innards
	0x40002134: "Crafting Tools",         // Crafting Kit
	0x4000218E: "Whetblades",             // Whetstone Knife
	0x400021D4: "Clues & Maps",           // Mirage Riddle
	0x40002292: "Sorcery Scrolls",        // Conspectus Scroll
	0x40002293: "Sorcery Scrolls",        // Royal House Scroll
	0x40002297: "Incantation Scrolls",    // Fire Monks' Prayerbook
	0x40002298: "Incantation Scrolls",    // Giant's Prayerbook
	0x40002299: "Incantation Scrolls",    // Godskin Prayerbook
	0x4000229A: "Incantation Scrolls",    // Two Fingers' Prayerbook
	0x4000229B: "Incantation Scrolls",    // Assassin's Prayerbook
	0x4000229C: "Incantation Scrolls",    // Erdtree Prayerbook
	0x4000229D: "Incantation Scrolls",    // Erdtree Codex
	0x4000229E: "Incantation Scrolls",    // Golden Order Principia
	0x4000229F: "Incantation Scrolls",    // Golden Order Principles
	0x400022A0: "Incantation Scrolls",    // Dragon Cult Prayerbook
	0x400022A1: "Incantation Scrolls",    // Ancient Dragon Prayerbook
	0x400022A2: "Sorcery Scrolls",        // Academy Scroll
	0x400022CE: "Crafting Bell Bearings", // Pidia's Bell Bearing
	0x400022CF: "Crafting Bell Bearings", // Seluvis's Bell Bearing
	0x400022D0: "Crafting Bell Bearings", // Patches' Bell Bearing
	0x400022D1: "Crafting Bell Bearings", // Sellen's Bell Bearing
	0x400022D3: "Crafting Bell Bearings", // D's Bell Bearing
	0x400022D4: "Crafting Bell Bearings", // Bernahl's Bell Bearing
	0x400022D5: "Crafting Bell Bearings", // Miriel's Bell Bearing
	0x400022D6: "Crafting Bell Bearings", // Gostoc's Bell Bearing
	0x400022D7: "Crafting Bell Bearings", // Thops's Bell Bearing
	0x400022D8: "Merchant Bell Bearings", // Kalé's Bell Bearing
	0x400022D9: "Merchant Bell Bearings", // Nomadic Merchant's Bell Bearing [1]
	0x400022DA: "Merchant Bell Bearings", // Nomadic Merchant's Bell Bearing [2]
	0x400022DB: "Merchant Bell Bearings", // Nomadic Merchant's Bell Bearing [3]
	0x400022DC: "Merchant Bell Bearings", // Nomadic Merchant's Bell Bearing [4]
	0x400022DD: "Merchant Bell Bearings", // Nomadic Merchant's Bell Bearing [5]
	0x400022DE: "Merchant Bell Bearings", // Isolated Merchant's Bell Bearing [1]
	0x400022DF: "Merchant Bell Bearings", // Isolated Merchant's Bell Bearing [2]
	0x400022E0: "Merchant Bell Bearings", // Nomadic Merchant's Bell Bearing [6]
	0x400022E1: "Merchant Bell Bearings", // Hermit Merchant's Bell Bearing [1]
	0x400022E2: "Merchant Bell Bearings", // Nomadic Merchant's Bell Bearing [7]
	0x400022E3: "Merchant Bell Bearings", // Nomadic Merchant's Bell Bearing [8]
	0x400022E4: "Merchant Bell Bearings", // Nomadic Merchant's Bell Bearing [9]
	0x400022E5: "Merchant Bell Bearings", // Nomadic Merchant's Bell Bearing [10]
	0x400022E6: "Merchant Bell Bearings", // Nomadic Merchant's Bell Bearing [11]
	0x400022E7: "Merchant Bell Bearings", // Isolated Merchant's Bell Bearing [3]
	0x400022E8: "Merchant Bell Bearings", // Hermit Merchant's Bell Bearing [2]
	0x400022E9: "Merchant Bell Bearings", // Abandoned Merchant's Bell Bearing
	0x400022EA: "Merchant Bell Bearings", // Hermit Merchant's Bell Bearing [3]
	0x400022EB: "Merchant Bell Bearings", // Imprisoned Merchant's Bell Bearing
	0x400022EC: "Crafting Bell Bearings", // Iji's Bell Bearing
	0x400022ED: "Crafting Bell Bearings", // Rogier's Bell Bearing
	0x400022EE: "Crafting Bell Bearings", // Blackguard's Bell Bearing
	0x400022EF: "Crafting Bell Bearings", // Corhyn's Bell Bearing
	0x400022F0: "Crafting Bell Bearings", // Gowry's Bell Bearing
	0x400022F1: "Crafting Bell Bearings", // Bone Peddler's Bell Bearing
	0x400022F2: "Crafting Bell Bearings", // Meat Peddler's Bell Bearing
	0x400022F3: "Crafting Bell Bearings", // Medicine Peddler's Bell Bearing
	0x400022F4: "Crafting Bell Bearings", // Gravity Stone Peddler's Bell Bearing
	0x400022F7: "Merchant Bell Bearings", // Smithing-Stone Miner's Bell Bearing [1]
	0x400022F8: "Merchant Bell Bearings", // Smithing-Stone Miner's Bell Bearing [2]
	0x400022F9: "Merchant Bell Bearings", // Smithing-Stone Miner's Bell Bearing [3]
	0x400022FA: "Merchant Bell Bearings", // Smithing-Stone Miner's Bell Bearing [4]
	0x400022FB: "Merchant Bell Bearings", // Somberstone Miner's Bell Bearing [1]
	0x400022FC: "Merchant Bell Bearings", // Somberstone Miner's Bell Bearing [2]
	0x400022FD: "Merchant Bell Bearings", // Somberstone Miner's Bell Bearing [3]
	0x400022FE: "Merchant Bell Bearings", // Somberstone Miner's Bell Bearing [4]
	0x400022FF: "Merchant Bell Bearings", // Somberstone Miner's Bell Bearing [5]
	0x40002300: "Merchant Bell Bearings", // Glovewort Picker's Bell Bearing [1]
	0x40002301: "Merchant Bell Bearings", // Glovewort Picker's Bell Bearing [2]
	0x40002302: "Merchant Bell Bearings", // Glovewort Picker's Bell Bearing [3]
	0x40002303: "Merchant Bell Bearings", // Ghost-Glovewort Picker's Bell Bearing [1]
	0x40002304: "Merchant Bell Bearings", // Ghost-Glovewort Picker's Bell Bearing [2]
	0x40002305: "Merchant Bell Bearings", // Ghost-Glovewort Picker's Bell Bearing [3]
	0x4000230A: "Whetblades",             // Iron Whetblade
	0x4000230B: "Whetblades",             // Red-Hot Whetblade
	0x4000230C: "Whetblades",             // Sanctified Whetblade
	0x4000230D: "Whetblades",             // Glintstone Whetblade
	0x4000230E: "Whetblades",             // Black Whetblade
	0x40002310: "Quest Items",            // Unalloyed Gold Needle
	0x40002311: "Quest Items",            // Valkyrie's Prosthesis
	0x40002313: "Quest Items",            // Beast Eye
	0x40002314: "Quest Items",            // Weathered Dagger
	0x40002458: "Cookbooks",              // Fugitive Warrior's Recipe [5]
	0x4000251C: "Containers",             // Cracked Pot
	0x4000251D: "Containers",             // Ritual Pot
	0x40002526: "Containers",             // Perfume Bottle
	0x4000272E: "Slot Upgrades",          // Memory Stone
	0x40002738: "Slot Upgrades",          // Talisman Pouch
	0x4000274C: "Quest Items",            // Dragon Heart
	0x40002756: "Quest Items",            // Lost Ashes of War
	0x40002760: "Great Runes",            // Great Rune of the Unborn
	0x401EA3C3: "Quest Items",            // Igon's Furled Finger
	0x401EA3C8: "Quest Items",            // Hole-Laden Necklace
	0x401EA3CB: "Quest Items",            // Heart of Bayle
	0x401EA3CC: "Clues & Maps",           // Cross-Marked Map
	0x401EA3CE: "Quest Items",            // Secret Rite Scroll
	0x401EA3D3: "Quest Items",            // Black Syrup
	0x401EA3D5: "Quest Items",            // Messmer's Kindling
	0x401EA3E1: "Quest Items",            // Larval Tear (DLC)
	0x401EA744: "Crafting Bell Bearings", // Moore's Bell Bearing
	0x401EA745: "Crafting Bell Bearings", // Ymir's Bell Bearing
	0x401EA746: "Crafting Bell Bearings", // Herbalist's Bell Bearing
	0x401EA747: "Crafting Bell Bearings", // Mushroom-Seller's Bell Bearing [1]
	0x401EA748: "Crafting Bell Bearings", // Mushroom-Seller's Bell Bearing [2]
	0x401EA749: "Crafting Bell Bearings", // Greasemonger's Bell Bearing
	0x401EA74A: "Crafting Bell Bearings", // Moldmonger's Bell Bearing
	0x401EA74B: "Crafting Bell Bearings", // Igon's Bell Bearing
	0x401EA74C: "Crafting Bell Bearings", // Spellmachinist's Bell Bearing
	0x401EA74D: "Crafting Bell Bearings", // String-Seller's Bell Bearing
	0x401EA99C: "Containers",             // Hefty Cracked Pot
}
