package main

// spellSubCategoryOverrides: real wiki.gg school sub-category for
// sorceries/incantations items.json entries, generated by
// tools/spell_categories (2026-08-01, see docs/ITEM_IDS.md and that
// tool's own doc comment for the wiki-category-membership methodology).
// Every sorcery/incantation now carries a school. Placidusax's Ruin
// has no wiki school but is filed under Dragon Communion by user
// preference (see generate.py). No invented catch-all buckets.
//
// Regenerate: cd tools/spell_categories && ../.venv/bin/python3 generate.py
var spellSubCategoryOverrides = map[uint32]string{
	0x40000FA0: "Glintstone Sorceries", // Glintstone Pebble
	0x40000FA1: "Glintstone Sorceries", // Great Glintstone Shard
	0x40000FAA: "Glintstone Sorceries", // Swift Glintstone Shard
	0x40000FB4: "Glintstone Sorceries", // Glintstone Cometshard
	0x40000FB5: "Glintstone Sorceries", // Comet
	0x40000FBE: "Glintstone Sorceries", // Shard Spiral
	0x40000FC8: "Glintstone Sorceries", // Glintstone Stars
	0x40000FD2: "Glintstone Sorceries", // Star Shower
	0x40000FDC: "Glintstone Sorceries", // Crystal Barrage
	0x40000FE6: "Glintstone Sorceries", // Glintstone Arc
	0x40000FF0: "Glintstone Sorceries", // Cannon of Haima
	0x40000FFA: "Glintstone Sorceries", // Crystal Burst
	0x40001004: "Glintstone Sorceries", // Shatter Earth
	0x4000100E: "Glintstone Sorceries", // Rock Blaster
	0x40001018: "Glintstone Sorceries", // Gavel of Haima
	0x40001022: "Glintstone Sorceries", // Terra Magica
	0x4000102C: "Glintstone Sorceries", // Starlight
	0x40001068: "Primeval Sorceries", // Comet Azur
	0x40001072: "Primeval Sorceries", // Founding Rain of Stars
	0x4000107C: "Primeval Sorceries", // Stars of Ruin
	0x400010CC: "Carian Sorceries", // Glintblade Phalanx
	0x400010CD: "Carian Sorceries", // Carian Phalanx
	0x400010CE: "Carian Sorceries", // Greatblade Phalanx
	0x40001108: "Carian Sorceries", // Rennala's Full Moon
	0x40001109: "Carian Sorceries", // Ranni's Dark Moon
	0x40001112: "Carian Sorceries", // Magic Downpour
	0x4000111C: "Carian Sorceries", // Loretta's Greatbow
	0x4000111D: "Carian Sorceries", // Loretta's Mastery
	0x40001126: "Carian Sorceries", // Magic Glintblade
	0x40001130: "Cold Sorceries", // Glintstone Icecrag
	0x4000113A: "Cold Sorceries", // Zamor Ice Storm
	0x40001144: "Cold Sorceries", // Freezing Mist
	0x4000114E: "Carian Sorceries", // Carian Greatsword
	0x4000114F: "Carian Sorceries", // Adula's Moonblade
	0x40001158: "Carian Sorceries", // Carian Slicer
	0x40001162: "Carian Sorceries", // Carian Piercer
	0x4000116C: "Glintstone Sorceries", // Scholar's Armament
	0x40001176: "Glintstone Sorceries", // Scholar's Shield
	0x40001180: "Carian Sorceries", // Lucidity
	0x4000118A: "Cold Sorceries", // Frozen Armament
	0x40001194: "Crystalian Sorceries", // Shattering Crystal
	0x4000119E: "Crystalian Sorceries", // Crystal Release
	0x400011A8: "Crystalian Sorceries", // Crystal Torrent
	0x400011F8: "Night Sorceries", // Ambush Shard
	0x40001202: "Night Sorceries", // Night Shard
	0x4000120C: "Night Sorceries", // Night Comet
	0x40001216: "Glintstone Sorceries", // Thops's Barrier
	0x40001220: "Carian Sorceries", // Carian Retaliation
	0x4000122A: "Night Sorceries", // Eternal Darkness
	0x40001234: "Night Sorceries", // Unseen Blade
	0x4000123E: "Night Sorceries", // Unseen Form
	0x4000125C: "Gravity Sorceries", // Meteorite
	0x4000125D: "Gravity Sorceries", // Meteorite of Astel
	0x40001266: "Gravity Sorceries", // Rock Sling
	0x40001270: "Gravity Sorceries", // Gravity Well
	0x40001271: "Gravity Sorceries", // Collapsing Stars
	0x400012C0: "Magma Sorceries", // Magma Shot
	0x400012CA: "Magma Sorceries", // Gelmir's Fury
	0x400012D4: "Magma Sorceries", // Roiling Magma
	0x400012DE: "Magma Sorceries", // Rykard's Rancor
	0x40001324: "Thorn Sorceries", // Briars of Sin
	0x4000132E: "Thorn Sorceries", // Briars of Punishment
	0x40001388: "Death Sorceries", // Rancorcall
	0x40001389: "Death Sorceries", // Ancient Death Rancor
	0x40001392: "Death Sorceries", // Explosive Ghostflame
	0x4000139C: "Death Sorceries", // Fia's Mist
	0x400013A6: "Death Sorceries", // Tibia's Summons
	0x400013B0: "Dragon Cult Incantations", // Death Lightning
	0x400013EC: "Claymen Sorceries", // Oracle Bubbles
	0x400013F6: "Claymen Sorceries", // Great Oracular Bubble
	0x40001770: "Flame Incantations", // Catch Flame
	0x40001771: "Flame Incantations", // O, Flame!
	0x4000177A: "Flame Incantations", // Flame Sling
	0x40001784: "Flame Incantations", // Flame, Fall Upon Them
	0x4000178E: "Flame Incantations", // Whirl, O Flame!
	0x40001798: "Flame Incantations", // Flame, Cleanse Me
	0x400017A2: "Flame Incantations", // Flame, Grant Me Strength
	0x400017AC: "Flame Incantations", // Flame, Protect Me
	0x400017D4: "Flame Incantations", // Giantsflame Take Thee
	0x400017DE: "Flame Incantations", // Flame of the Fell God
	0x400017E8: "Flame Incantations", // Burn, O Flame!
	0x40001842: "Godslayer Incantations", // Black Flame
	0x4000184C: "Flame Incantations", // Surge, O Flame!
	0x40001856: "Godslayer Incantations", // Scouring Black Flame
	0x40001860: "Godslayer Incantations", // Black Flame Ritual
	0x4000186A: "Godslayer Incantations", // Black Flame Blade
	0x40001874: "Godslayer Incantations", // Black Flame's Protection
	0x4000187E: "Godslayer Incantations", // Noble Presence
	0x4000189C: "Blood Oath Incantations", // Bloodflame Talons
	0x400018A6: "Blood Oath Incantations", // Bloodboon
	0x400018B0: "Blood Oath Incantations", // Bloodflame Blade
	0x400018BA: "Erdtree Worship Incantations", // Barrier of Gold
	0x400018C4: "Erdtree Worship Incantations", // Protection of the Erdtree
	0x40001900: "Two Fingers Incantations", // Rejection
	0x4000190A: "Erdtree Worship Incantations", // Wrath of Gold
	0x40001914: "Two Fingers Incantations", // Urgent Heal
	0x40001915: "Two Fingers Incantations", // Heal
	0x40001916: "Two Fingers Incantations", // Great Heal
	0x40001917: "Two Fingers Incantations", // Lord's Heal
	0x40001918: "Erdtree Incantations", // Erdtree Heal
	0x4000191E: "Erdtree Incantations", // Blessing's Boon
	0x4000191F: "Erdtree Incantations", // Blessing of the Erdtree
	0x40001928: "Two Fingers Incantations", // Cure Poison
	0x40001929: "Two Fingers Incantations", // Lord's Aid
	0x40001932: "Two Fingers Incantations", // Flame Fortification
	0x4000193C: "Two Fingers Incantations", // Magic Fortification
	0x40001946: "Two Fingers Incantations", // Lightning Fortification
	0x40001950: "Two Fingers Incantations", // Divine Fortification
	0x4000195A: "Two Fingers Incantations", // Lord's Divine Fortification
	0x40001964: "Night Sorceries", // Night Maiden's Mist
	0x4000196E: "Two Fingers Incantations", // Assassin's Approach
	0x40001978: "Two Fingers Incantations", // Shadow Bait
	0x40001982: "Two Fingers Incantations", // Darkness
	0x400019C8: "Erdtree Worship Incantations", // Golden Vow
	0x40001A2C: "Golden Order Incantations", // Discus of Light
	0x40001A2D: "Golden Order Incantations", // Triple Rings of Light
	0x40001A36: "Golden Order Incantations", // Radagon's Rings of Light
	0x40001A40: "Erdtree Incantations", // Elden Stars
	0x40001A4A: "Golden Order Incantations", // Law of Regression
	0x40001A54: "Golden Order Incantations", // Immutable Shield
	0x40001A5E: "Golden Order Incantations", // Litany of Proper Death
	0x40001A68: "Golden Order Incantations", // Law of Causality
	0x40001A72: "Golden Order Incantations", // Order's Blade
	0x40001A7C: "Golden Order Incantations", // Order Healing
	0x40001A90: "Bestial Incantations", // Bestial Sling
	0x40001A9A: "Bestial Incantations", // Stone of Gurranq
	0x40001AA4: "Bestial Incantations", // Beast Claw
	0x40001AAE: "Bestial Incantations", // Gurranq's Beast Claw
	0x40001AB8: "Bestial Incantations", // Bestial Vitality
	0x40001AC2: "Bestial Incantations", // Bestial Constitution
	0x40001AF4: "Dragon Cult Incantations", // Lightning Spear
	0x40001AFE: "Dragon Cult Incantations", // Ancient Dragons' Lightning Strike
	0x40001B08: "Dragon Cult Incantations", // Lightning Strike
	0x40001B09: "Dragon Cult Incantations", // Frozen Lightning Spear
	0x40001B12: "Dragon Cult Incantations", // Honed Bolt
	0x40001B1C: "Dragon Cult Incantations", // Ancient Dragons' Lightning Spear
	0x40001B1D: "Dragon Cult Incantations", // Fortissax's Lightning Spear
	0x40001B26: "Dragon Cult Incantations", // Lansseax's Glaive
	0x40001B30: "Dragon Cult Incantations", // Electrify Armament
	0x40001B3A: "Dragon Cult Incantations", // Vyke's Dragonbolt
	0x40001B3B: "Dragon Cult Incantations", // Dragonbolt Blessing
	0x40001B58: "Dragon Communion Incantations", // Dragonfire
	0x40001B59: "Dragon Communion Incantations", // Agheel's Flame
	0x40001B62: "Dragon Communion Incantations", // Magma Breath
	0x40001B63: "Dragon Communion Incantations", // Theodorix's Magma
	0x40001B6C: "Dragon Communion Incantations", // Dragonice
	0x40001B6D: "Dragon Communion Incantations", // Borealis's Mist
	0x40001B76: "Dragon Communion Incantations", // Rotten Breath
	0x40001B77: "Dragon Communion Incantations", // Ekzykes's Decay
	0x40001B80: "Dragon Communion Incantations", // Glintstone Breath
	0x40001B81: "Dragon Communion Incantations", // Smarag's Glintstone Breath
	0x40001B8A: "Dragon Communion Incantations", // Placidusax's Ruin
	0x40001B94: "Dragon Communion Incantations", // Dragonclaw
	0x40001BA8: "Dragon Communion Incantations", // Dragonmaw
	0x40001BB2: "Dragon Communion Incantations", // Greyoll's Roar
	0x40001C20: "Servants of Rot Incantations", // Pest Threads
	0x40001C2A: "Blood Oath Incantations", // Swarm of Flies
	0x40001C34: "Servants of Rot Incantations", // Poison Mist
	0x40001C3E: "Servants of Rot Incantations", // Poison Armament
	0x40001C48: "Servants of Rot Incantations", // Scarlet Aeonia
	0x40001C84: "Three Fingers Incantations", // Inescapable Frenzy
	0x40001C8E: "Three Fingers Incantations", // The Flame of Frenzy
	0x40001C8F: "Three Fingers Incantations", // Unendurable Frenzy
	0x40001C98: "Three Fingers Incantations", // Frenzied Burst
	0x40001CA2: "Three Fingers Incantations", // Howl of Shabriri
	0x40001D4C: "Erdtree Incantations", // Aspects of the Crucible: Tail
	0x40001D56: "Erdtree Incantations", // Aspects of the Crucible: Horns
	0x40001D60: "Erdtree Incantations", // Aspects of the Crucible: Breath
	0x40001D6A: "Erdtree Incantations", // Black Blade
	0x40001EDC: "Flame Incantations", // Fire's Deadly Sin
	0x40001EDF: "Erdtree Worship Incantations", // Golden Lightning Fortification
	0x401E954C: "Carian Sorceries", // Miriam's Vanishing
	0x401E9556: "Carian Sorceries", // Glintblade Trio
	0x401E9560: "Carian Sorceries", // Rellana's Twin Moons
	0x401E9614: "Finger Sorceries", // Glintstone Nail
	0x401E961E: "Finger Sorceries", // Glintstone Nails
	0x401E96DC: "Gravity Sorceries", // Blades of Stone
	0x401E96E6: "Gravity Sorceries", // Gravitational Missile
	0x401E97A4: "Thorn Sorceries", // Mantle of Thorns
	0x401E97AE: "Thorn Sorceries", // Impenetrable Thorns
	0x401E9808: "Death Sorceries", // Rings of Spectral Light
	0x401E9CB8: "Death Sorceries", // Vortex of Putrescence
	0x401E9CC2: "Death Sorceries", // Mass of Putrescence
	0x401E9D1C: "Blood Oath Incantations", // Furious Blade of Ansbach
	0x401E9D80: "Erdtree Incantations", // Heal from Afar
	0x401E9E7A: "Erdtree Incantations", // Aspects of the Crucible: Thorns
	0x401E9E84: "Erdtree Incantations", // Aspects of the Crucible: Bloom
	0x401E9E8E: "Erdtree Incantations", // Minor Erdtree
	0x401E9E98: "Erdtree Incantations", // Land of Shadow
	0x401E9EA2: "Erdtree Incantations", // Wrath from Afar
	0x401E9EAC: "Miquella's Incantations", // Light of Miquella
	0x401E9EB6: "Miquella's Incantations", // Multilayered Ring of Light
	0x401E9F10: "Bear Communion Incantations", // Roar of Rugalea
	0x401E9F74: "Dragon Cult Incantations", // Knight's Lightning Spear
	0x401E9F7E: "Dragon Cult Incantations", // Dragonbolt of Florissax
	0x401E9F88: "Dragon Cult Incantations", // Electrocharge
	0x401E9FD8: "Dragon Communion Incantations", // Bayle's Tyranny
	0x401E9FE2: "Dragon Communion Incantations", // Bayle's Flame Lightning
	0x401E9FEC: "Dragon Communion Incantations", // Ghostflame Breath
	0x401EA0A0: "Servants of Rot Incantations", // Rotten Butterflies
	0x401EA0AA: "Servants of Rot Incantations", // Pest-Thread Spears
	0x401EA104: "Three Fingers Incantations", // Midra's Flame of Frenzy
	0x401EA172: "Finger Sorceries", // Fleeting Microcosm
	0x401EA17C: "Finger Sorceries", // Cherishing Fingers
	0x401EA230: "Divine Beast Incantations", // Watchful Spirit
	0x401EA294: "Spiral Incantations", // Golden Arcs
	0x401EA29E: "Spiral Incantations", // Giant Golden Arc
	0x401EA2A8: "Spiral Incantations", // Spira
	0x401EA2B2: "Divine Beast Incantations", // Divine Beast Tornado
	0x401EA2BC: "Divine Beast Incantations", // Divine Bird Feathers
	0x401EA2F8: "Messmer's Flame Incantations", // Fire Serpent
	0x401EA302: "Messmer's Flame Incantations", // Rain of Fire
	0x401EA30C: "Messmer's Flame Incantations", // Messmer's Orb
}
