package catalog

// CI-runnable (no fixture): weapon_reinforce_rates.json is embedded static
// data (generated by tools/weapon_reinforce_rates_extract from the fixture's
// regulation.bin, see docs/ITEM_IDS.md), decoded via New()/loadReinforceRates.

import (
	"math"
	"reflect"
	"testing"
)

// TestReinforcedWeaponScalesByLevel verifies the item-info popup's "+N" stat
// scaling: a standard weapon's base (+0) attack/scaling times the
// ReinforceParamWeapon rate curve. Longsword (id 1030000, reinforceTypeId 0,
// the +25 standard curve) at +25 must be base*2.45 attack / base*1.5 Str-Dex
// scaling (the confirmed type-0 +25 rates); +0 and an unknown item return the
// base untouched; a level past the max clamps to it.
func TestReinforcedWeaponScalesByLevel(t *testing.T) {
	c, err := New()
	if err != nil {
		t.Fatal(err)
	}
	const longsword = int64(1030000)
	base, ok := c.ItemDetails(longsword)
	if !ok || base.Weapon == nil {
		t.Fatalf("Longsword (%d) has no weapon detail", longsword)
	}
	bw := *base.Weapon

	// +0 is a no-op.
	if got := c.ReinforcedWeapon(longsword, 0, bw); !reflect.DeepEqual(got, bw) {
		t.Errorf("ReinforcedWeapon(+0) changed the base stats: %+v vs %+v", got, bw)
	}
	// An unknown item id is a no-op too (nothing to scale by).
	if got := c.ReinforcedWeapon(999999999, 25, bw); !reflect.DeepEqual(got, bw) {
		t.Errorf("ReinforcedWeapon(unknown id) changed the base stats")
	}

	want := func(v uint32, rate float64) uint32 { return uint32(math.Round(float64(v) * rate)) }
	w25 := c.ReinforcedWeapon(longsword, 25, bw)
	if w25.PhysDamage != want(bw.PhysDamage, 2.45) {
		t.Errorf("+25 PhysDamage = %d, want %d (base %d * 2.45)", w25.PhysDamage, want(bw.PhysDamage, 2.45), bw.PhysDamage)
	}
	if w25.ScaleStr != want(bw.ScaleStr, 1.5) || w25.ScaleDex != want(bw.ScaleDex, 1.5) {
		t.Errorf("+25 Str/Dex scaling = %d/%d, want %d/%d (base *1.5)",
			w25.ScaleStr, w25.ScaleDex, want(bw.ScaleStr, 1.5), want(bw.ScaleDex, 1.5))
	}
	// A level past the +25 max clamps to +25, not out-of-range panic / no-op.
	if got := c.ReinforcedWeapon(longsword, 99, bw); !reflect.DeepEqual(got, w25) {
		t.Errorf("ReinforcedWeapon(+99) = %+v, want the +25 clamp %+v", got, w25)
	}
	// Scaling actually grew (guards against a silently-empty curve).
	if bw.PhysDamage > 0 && w25.PhysDamage <= bw.PhysDamage {
		t.Errorf("+25 attack (%d) did not exceed +0 (%d)", w25.PhysDamage, bw.PhysDamage)
	}
}
